python phc/run_hydra.py \
env.num_envs=128 \
im_eval=True \
learning=im_mcp_big \
learning.params.network.ending_act=False \
exp_name=phc_comp_kp_2 \
env.obs_v=7 \
env=env_im_getup_mcp \
robot=smpl_humanoid \
robot.real_weight_porpotion_boxes=False \
env.motion_file=./data/amass/pkls/amass_isaac_im_train_take6_upright_slim.pkl \
env.models=['output/HumanoidIm/phc_kp_2/Humanoid.pth'] \
env.num_prim=3 \
env.add_obs_noise=False \
headless=False \
epoch=-1 \
test=True \
dataset=True \
mlp=False